Repository maple-labs/proxy-factory, pull requests merged in 2021-12, with the labels that each got.

#29 fix: Add contract check on fallback
  contracts/Proxy.sol
  contracts/test/ProxyFactory.t.sol
  contracts/test/mocks/Mocks.sol
Labels: Status: Ready for Review

#31 fix: Added protection to avoid double register implementation
  contracts/ProxyFactory.sol
  contracts/test/ProxyFactory.t.sol
Labels: Priority: Low, Status: Ready for Review

#30 feat: Added missing unit tests (SC-4141)
  contracts/test/ProxyFactory.t.sol
Labels: Priority: High, Status: Ready for Review

#33 fix: Constructor validation in Proxy (C4 #15)
  contracts/Proxy.sol
  contracts/test/ProxyFactory.t.sol
Labels: Priority: Medium, Status: Ready for Review

#34 chore: Cleanup everything and add inline comments
  .github/PULL_REQUEST_TEMPLATE.md
  config/ci.json
  config/dev.json
  config/prod.json
  contracts/Proxied.sol
  contracts/Proxy.sol
  contracts/ProxyFactory.sol
  contracts/test/ProxyFactory.t.sol
  contracts/test/mocks/Mocks.sol
Labels: Priority: Medium, Status: On Hold

#37 formatting: Update solc, param underscores, licensing
  README.md
  contracts/Proxied.sol
  contracts/Proxy.sol
  contracts/ProxyFactory.sol
  contracts/SlotManipulatable.sol
  contracts/interfaces/IDefaultImplementationBeacon.sol
  contracts/interfaces/IProxied.sol
  contracts/test/ProxyFactory.t.sol
  contracts/test/SlotManipulatable.t.sol
  contracts/test/mocks/Mocks.sol
Labels: Priority: High, Status: Ready for Review

#38 feat: Use `code.length` instead of `extcodesize`
  contracts/Proxy.sol
  contracts/ProxyFactory.sol
  contracts/test/ProxyFactory.t.sol
Labels: Priority: High, Status: Ready for Review

#39 chore: Natspec, checksums, whitespace, cleanup
  .circleci/config.yml
  .gitignore
  README.md
  contracts/ProxiedInternals.sol
  contracts/Proxy.sol
  contracts/ProxyFactory.sol
  contracts/SlotManipulatable.sol
  contracts/interfaces/IDefaultImplementationBeacon.sol
  contracts/interfaces/IProxied.sol
  contracts/test/ProxyFactory.t.sol
  contracts/test/mocks/Mocks.sol
Labels: Priority: Medium, Status: On Hold
