Repository maple-labs/proxy-factory, pull requests merged in 2021-09, with the labels that each got.

#10 feat: Increase unit test coverage (SC-3670)
  config/ci.json
  config/dev.json
  contracts/ProxyFactory.sol
  contracts/test/SlotManipulatable.t.sol
  contracts/test/Test.t.sol
  contracts/test/mocks/Mocks.sol
Labels: Status: Ready for Review

#14 chore: _implementation -> _implementationOf
  contracts/ProxyFactory.sol
  contracts/test/mocks/Mocks.sol
Labels: Priority: Medium, Status: Ready for Review

#13 fix: require in _newInstanceWithSalt and more functional
  contracts/ProxyFactory.sol
  contracts/test/mocks/Mocks.sol
Labels: Priority: Medium, Status: Ready for Review

#12 chore: Standardize Argument Styles
  contracts/Proxied.sol
  contracts/ProxyFactory.sol
  contracts/SlotManipulatable.sol
  contracts/interfaces/IProxied.sol
  contracts/test/SlotManipulatable.t.sol
  contracts/test/Test.t.sol
  contracts/test/mocks/Mocks.sol
Labels: Priority: Medium, Status: Ready for Review

#16 refactor: More Cleanup
  contracts/Proxied.sol
  contracts/Proxy.sol
  contracts/ProxyFactory.sol
  contracts/SlotManipulatable.sol
  contracts/interfaces/IProxied.sol
  contracts/test/mocks/Mocks.sol
Labels: Priority: High, Status: Ready for Review

#18 chore: Critical ACL warning in natspec
  contracts/interfaces/IProxied.sol
Labels: Priority: Medium, Status: Ready for Review

#17 feat: Remove requires from Proxied
  contracts/Proxied.sol
  contracts/interfaces/IProxied.sol
  contracts/test/mocks/Mocks.sol
Labels: Priority: Medium, Status: Ready for Review

#19 chore: Mock fix
  contracts/test/mocks/Mocks.sol
Labels: Priority: Medium, Status: Ready for Review

#20 feat: `_isInstance`
  contracts/ProxyFactory.sol
  contracts/test/Test.t.sol
  contracts/test/mocks/Mocks.sol
Labels: Priority: Medium, Status: Ready for Review
